name: scOmni
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.6.15=hbd8a1cb_0
  - ld_impl_linux-64=2.43=h1423503_5
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgomp=15.1.0=h767d61c_2
  - liblzma=5.8.1=hb9d3cd8_2
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.50.1=hee588c1_0
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.5.0=h7b32b05_1
  - pip=25.1.1=pyh8b19718_0
  - python=3.10.18=hd6af730_0_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - absl-py==2.3.0
      - adjusttext==1.3.0
      - aiobotocore==2.23.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.13
      - aioitertools==0.12.0
      - aiosignal==1.3.2
      - anndata==0.11.4
      - annotated-types==0.7.0
      - annoy==1.17.3
      - antlr-denter==1.3.1
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - array-api-compat==1.12.0
      - asciitree==0.3.3
      - astroid==3.3.10
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - automata-lib==9.0.0
      - biothings-client==0.4.1
      - bleach==6.2.0
      - bokeh==3.7.3
      - botocore==1.38.27
      - cached-method==0.1.0
      - certifi==2025.6.15
      - charset-normalizer==3.4.2
      - chex==0.1.89
      - click==8.2.1
      - cloudpickle==3.1.1
      - colorcet==3.1.0
      - comm==0.2.2
      - contourpy==1.3.2
      - curlify==2.2.1
      - cycler==0.12.1
      - dask==2024.11.2
      - dask-expr==1.1.19
      - dask-image==2024.5.3
      - datashader==0.18.1
      - debugpy==1.8.14
      - decorator==5.2.1
      - dill==0.4.0
      - distro==1.9.0
      - dnspython==2.7.0
      - docopt==0.6.2
      - docrep==0.3.2
      - et-xmlfile==2.0.0
      - etils==1.12.2
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fasteners==0.19
      - filelock==3.18.0
      - flax==0.10.6
      - fonttools==4.58.4
      - frozendict==2.4.6
      - frozenlist==1.7.0
      - fsspec==2025.5.1
      - ftpretty==0.4.0
      - future==1.0.0
      - geopandas==1.1.0
      - goatools==1.4.12
      - grpcio==1.73.0
      - h11==0.16.0
      - h5py==3.14.0
      - h5sparse==0.1.0
      - harmony-py==1.2.0
      - harmonypy==0.0.10
      - holoviews==1.20.2
      - httpcore==1.0.9
      - httpx==0.28.1
      - humanize==4.12.3
      - hyperopt==0.1.2
      - idna==3.10
      - igraph==0.11.9
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - inflect==7.5.0
      - ipykernel==6.29.5
      - ipython==8.37.0
      - isort==6.0.1
      - jax==0.6.2
      - jaxlib==0.6.2
      - jedi==0.19.2
      - jinja2==3.1.6
      - jiter==0.10.0
      - jmespath==1.0.1
      - joblib==1.5.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - legacy-api-wrap==1.4.1
      - leidenalg==0.10.2
      - lightning==2.5.1.post0
      - lightning-utilities==0.14.3
      - linkify-it-py==2.0.3
      - llvmlite==0.44.0
      - locket==1.0.0
      - louvain==0.8.2
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - matplotlib-inline==0.1.7
      - matplotlib-scalebar==0.9.0
      - mccabe==0.7.0
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - mizani==0.13.5
      - ml-collections==1.1.0
      - ml-dtypes==0.5.1
      - more-itertools==10.7.0
      - mpmath==1.3.0
      - msgpack==1.1.1
      - mudata==0.3.2
      - multidict==6.4.4
      - multipledispatch==1.0.0
      - multiscale-spatial-image==2.0.2
      - mygene==3.2.2
      - narwhals==1.43.0
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numba==0.61.2
      - numcodecs==0.13.1
      - numexpr==2.11.0
      - numpy==2.2.6
      - numpyro==0.18.0
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - ome-zarr==0.11.1
      - omnipath==1.0.10
      - openai==1.88.0
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - optax==0.2.5
      - orbax-checkpoint==0.11.15
      - packaging==24.2
      - pandas==2.3.0
      - panel==1.7.1
      - param==2.2.1
      - parso==0.8.4
      - partd==1.4.2
      - patsy==1.0.1
      - pexpect==4.9.0
      - pillow==11.2.1
      - pims==0.7
      - platformdirs==4.3.8
      - plotnine==0.14.5
      - pockets==0.9.1
      - pooch==1.8.2
      - progressbar2==4.2.0
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==20.0.0
      - pyct==0.5.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pydot==4.0.1
      - pygments==2.19.1
      - pyliger==0.2.4
      - pylint==3.3.7
      - pymongo==4.13.2
      - pynndescent==0.5.13
      - pyogrio==0.11.0
      - pyparsing==3.2.3
      - pyproj==3.7.1
      - pyro-api==0.1.2
      - pyro-ppl==1.9.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==0.20.0
      - python-igraph==0.11.9
      - python-utils==3.9.1
      - pytorch-lightning==2.5.1.post0
      - pytz==2025.2
      - pyviz-comms==3.0.5
      - pyyaml==6.0.2
      - pyzmq==27.0.0
      - requests==2.32.4
      - rich==14.0.0
      - s3fs==2025.5.1
      - scanpy==1.11.2
      - scikit-image==0.25.2
      - scikit-learn==1.7.0
      - scikit-misc==0.5.1
      - scipy==1.15.3
      - scvi==0.6.8
      - scvi-tools==1.3.1.post1
      - seaborn==0.13.2
      - session-info2==0.1.2
      - shapely==2.0.7
      - simplejson==3.20.1
      - six==1.17.0
      - slicerator==1.1.0
      - sniffio==1.3.1
      - sparse==0.17.0
      - spatial-image==1.2.1
      - spatialdata==0.4.0
      - sphinxcontrib-napoleon==0.7
      - squidpy==1.6.5
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - sympy==1.14.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.75
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tomli==2.2.1
      - tomlkit==0.13.3
      - toolz==1.0.0
      - torch==2.7.1
      - torchmetrics==1.7.3
      - tornado==6.5.1
      - tqdm==4.67.1
      - traitlets==5.14.3
      - treescope==0.1.9
      - triton==3.3.1
      - typeguard==4.4.3
      - typing-extensions==4.14.0
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uc-micro-py==1.0.3
      - umap-learn==0.5.7
      - urllib3==2.4.0
      - validators==0.35.0
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xarray==2024.11.0
      - xarray-dataclasses==1.9.1
      - xarray-schema==0.0.3
      - xarray-spatial==0.4.0
      - xlrd==2.0.2
      - xlsxwriter==3.2.5
      - xyzservices==2025.4.0
      - yarl==1.20.1
      - zarr==2.18.3
      - zipp==3.23.0
prefix: /opt/conda/envs/scOmni
